(executable
 (name pp)
 (modules pp)
 (libraries ppx_cstruct))

(executable
 (name gen_tests)
 (modules gen_tests))

(env
 (_
  (env-vars
   (OCAML_COLOR never)
   (OCAML_ERROR_STYLE short))))

(include dune.inc)

(rule
 (targets dune.inc.gen)
 (deps
  (source_tree .))
 (action
  (with-stdout-to
   %{targets}
   (run ./gen_tests.exe))))

(rule
 (alias runtest)
 (action
  (diff dune.inc dune.inc.gen)))
