kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install afl
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin && opam update
  - opam switch 4.07+afl
  - opam pin add -n .
  - opam depext cstruct-async cstruct-lwt cstruct-unix cstruct ppx_cstruct
  - opam install -y .
  - opam install -y crowbar fmt
  - opam exec -- dune build fuzz/fuzz.exe
  - mkdir out && mkdir in && echo bactrian > in/test
  - opam pin add -y bun https://github.com/yomimono/ocaml-bun.git
  - opam exec -- bun -i in -o out -- ./_build/default/fuzz/fuzz.exe
---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: ocaml/opam2:4.07
  commands:
  - sudo apt-get update && sudo apt-get -y install afl
  - sudo chown -R opam .
  - git -C /home/opam/opam-repository pull origin && opam update
  - opam switch 4.07+afl
  - opam pin add -n .
  - opam depext cstruct-async cstruct-lwt cstruct-unix cstruct ppx_cstruct
  - opam install -y .
  - opam install -y crowbar fmt
  - opam exec -- dune build fuzz/fuzz.exe
  - mkdir out && mkdir in && echo bactrian > in/test
  - opam pin add -y bun https://github.com/yomimono/ocaml-bun.git
  - opam exec -- bun -i in -o out -- ./_build/default/fuzz/fuzz.exe

