#!/bin/sh -e

case $1 in
  clean) rm -f ppx/ppx_cstruct.ml; exit 0 ;;
  conf) ;;
  *) echo "Usage: $0 [conf|clean]"; exit 1 ;;
esac

V=`ocamlc -version`
case $V in
4.02*) SRC=402 ;;
4.03*) SRC=403 ;;
4.04*) SRC=404 ;;
*) echo Unsupported OCaml version $V; exit 1 ;;
esac
echo "(* Do not edit this autogenerated file, edit ppx_cstruct.$SRC.ml instead *)" > ppx/ppx_cstruct.ml
cat ppx/ppx_cstruct.$SRC.ml >> ppx/ppx_cstruct.ml
echo Generating ppx/ppx_cstruct.ml from ppx/ppx_cstruct.$SRC.ml
