name: Cstruct
on: [push, pull_request]
jobs:
  latest:
    name: Latest
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [ '5', '4', '4.10.0', '4.08.1' ]
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          operating-system: macos-latest
          ocaml-version: ['4.10.0', '4.08.1']
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
    - run: opam install . --deps-only --with-test
    - name: Build
      run: opam exec -- dune build
    - run: opam exec -- dune runtest
  ppx:
    name: PPX
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [ '5', '4', '4.10.0', '4.08.1' ]
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        exclude:
          operating-system: macos-latest
          ocaml-version: ['4.10.0', '4.08.1']
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
    - run: opam pin add -n .
    - name: Build
      run: opam install -t ppx_cstruct
  async:
    name: Async
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        ocaml-version: [ '5', '4', '4.10.0', '4.08.1' ]
        operating-system: [macos-latest, ubuntu-latest]
        exclude:
          operating-system: macos-latest
          ocaml-version: ['4.10.0', '4.08.1']
    steps:
    - uses: actions/checkout@v4
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-version }}
    - run: opam pin add -n .
    - name: Dependencies
      run: opam install -t cstruct-async
