name: Cstruct
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.ocaml-compiler }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ocaml-compiler:
          - "5.5"
          - "5.1"
          - "4.14"
    steps:
      - uses: actions/checkout@v6
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
      - run: opam install . --deps-only --with-test
      - run: opam exec -- dune build @all
      - run: opam exec -- dune runtest
